  spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/spring
        username: postgres
        password: postgres
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                default_schema: public
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                lob:
                    non_contextual_creation: true